Update wine.yml

diff --git a/.github/workflows/wine.yml b/.github/workflows/wine.yml
--- a/.github/workflows/wine.yml
+++ b/.github/workflows/wine.yml
@@ -108,6 +108,7 @@ jobs:
             libgstreamer1.0-dev:arm64 \
             libgstreamer-plugins-base1.0-dev:arm64 \
             libgstreamer-plugins-bad1.0-dev:arm64 \
+            gstreamer1.0-tools \
             libudev-dev:arm64 \
             libunwind-dev:arm64 \
             libsdl2-dev:arm64 \
@@ -133,6 +134,15 @@ jobs:
           tar -xJf ${{ env.LLVMMINGW_NAME }}.tar.xz
           rm ${{ env.LLVMMINGW_NAME }}.tar.xz
           echo "/opt/${{ env.LLVMMINGW_NAME }}/bin" >> $GITHUB_PATH
+
+          pkg-config --exists gstreamer-1.0 || echo "gstreamer-1.0 not found"
+          pkg-config --exists gstreamer-base-1.0 || echo "gstreamer-base-1.0 not found"
+          pkg-config --modversion gstreamer-1.0 || echo "version check failed"
+  
+          if ! pkg-config --exists gstreamer-base-1.0; then
+          export CFLAGS="$CFLAGS -I/usr/include/aarch64-linux-gnu/gstreamer-1.0"
+          export LDFLAGS="$LDFLAGS -L/usr/lib/aarch64-linux-gnu"
+          fi
       # ------------------------------------------------------------
       # 4. 设置中文语言环境
       # ------------------------------------------------------------
